import { join } from "node:path";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { stringify as stringifyYaml, parse as parseYaml } from "yaml";
import type { SkillPackage, ConfigInput } from "./types.js";

// ---------------------------------------------------------------------------
// Config Generation
// ---------------------------------------------------------------------------

export interface ConfigGeneratorInput {
  /** Project-level config from skillsync.yaml `config` section. */
  manifestConfig: Record<string, Record<string, unknown>>;
  /** Installed skill packages (for config_input defaults and validation). */
  installedSkills: SkillPackage[];
}

/**
 * Generate the merged skillsync.config.yaml content.
 *
 * Layering order (later wins):
 * 1. Skill-declared defaults (from skill.yaml config_inputs)
 * 2. Project manifest config values (from skillsync.yaml config section)
 *
 * This means project config always overrides skill defaults, which is the
 * expected behavior for "generic skill + project-specific settings."
 */
export function generateConfig(
  input: ConfigGeneratorInput,
): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};

  // Layer 1: Collect defaults from all installed skills
  for (const pkg of input.installedSkills) {
    if (!pkg.meta?.configInputs?.length) continue;

    const skillConfig: Record<string, unknown> = {};
    for (const ci of pkg.meta.configInputs) {
      if (ci.default !== undefined) {
        const parts = ci.key.split(".");
        // Support dotted keys: "test.runner" → config.test.runner
        if (parts.length === 2 && parts[0] === pkg.name) {
          skillConfig[parts[1]!] = ci.default;
        } else {
          skillConfig[ci.key] = ci.default;
        }
      }
    }
    if (Object.keys(skillConfig).length > 0) {
      result[pkg.name] = skillConfig;
    }
  }

  // Layer 2: Override with project manifest config
  for (const [skillName, config] of Object.entries(input.manifestConfig)) {
    if (!result[skillName]) {
      result[skillName] = {};
    }
    Object.assign(result[skillName]!, config);
  }

  return result;
}

/**
 * Write the generated skillsync.config.yaml into a target directory.
 */
export async function writeProjectConfig(
  targetDir: string,
  config: Record<string, Record<string, unknown>>,
): Promise<string> {
  await mkdir(targetDir, { recursive: true });
  const configPath = join(targetDir, "skillsync.config.yaml");
  const content =
    "# Generated by skillsync. Do not edit manually.\n# Re-run `skillsync sync` to regenerate.\n" +
    stringifyYaml(config);
  await writeFile(configPath, content, "utf-8");
  return configPath;
}

/**
 * Validate that manifest config values match declared config_inputs.
 * Returns warnings for unknown keys and type mismatches.
 */
export function validateConfigOverrides(
  manifestConfig: Record<string, Record<string, unknown>>,
  installedSkills: SkillPackage[],
): string[] {
  const warnings: string[] = [];
  const skillMap = new Map(installedSkills.map((s) => [s.name, s]));

  for (const [skillName, config] of Object.entries(manifestConfig)) {
    const pkg = skillMap.get(skillName);
    if (!pkg) {
      warnings.push(
        `Config for "${skillName}" has no matching installed skill`,
      );
      continue;
    }

    if (!pkg.meta?.configInputs?.length) {
      // Skill doesn't declare config_inputs — config values are passthrough
      continue;
    }

    const declaredKeys = new Set(
      pkg.meta.configInputs.map((ci) => {
        const parts = ci.key.split(".");
        return parts.length === 2 && parts[0] === skillName
          ? parts[1]!
          : ci.key;
      }),
    );

    for (const key of Object.keys(config)) {
      if (!declaredKeys.has(key)) {
        warnings.push(
          `Config key "${skillName}.${key}" is not declared in skill's config_inputs`,
        );
      }
    }
  }

  return warnings;
}
