import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import type { SkillPackage } from "./types.js";

// ---------------------------------------------------------------------------
// Config Generation
// ---------------------------------------------------------------------------

export interface ConfigGeneratorInput {
  /** Project-level config from skill-sync.yaml `config` section. */
  manifestConfig: Record<string, Record<string, unknown>>;
  /** Installed skill packages (for config_input defaults and validation). */
  installedSkills: SkillPackage[];
}

/**
 * Generate the merged skill-sync.config.yaml content.
 *
 * Layering order (later wins):
 * 1. Skill-declared defaults (from skill.yaml config_inputs)
 * 2. Project manifest config values (from skill-sync.yaml config section)
 *
 * This means project config always overrides skill defaults, which is the
 * expected behavior for "generic skill + project-specific settings."
 */
export function generateConfig(
  input: ConfigGeneratorInput,
): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};

  // Layer 1: Collect defaults from all installed skills
  for (const pkg of input.installedSkills) {
    if (!pkg.meta?.configInputs?.length) continue;

    const skillConfig: Record<string, unknown> = {};
    for (const ci of pkg.meta.configInputs) {
      if (ci.default !== undefined) {
        const parts = ci.key.split(".");
        // Support dotted keys: "test.runner" → config.test.runner
        if (parts.length === 2 && parts[0] === pkg.name) {
          skillConfig[parts[1]!] = ci.default;
        } else {
          skillConfig[ci.key] = ci.default;
        }
      }
    }
    if (Object.keys(skillConfig).length > 0) {
      result[pkg.name] = skillConfig;
    }
  }

  // Layer 2: Override with project manifest config
  for (const [skillName, config] of Object.entries(input.manifestConfig)) {
    if (!result[skillName]) {
      result[skillName] = {};
    }
    Object.assign(result[skillName]!, config);
  }

  // Canonicalize: sort skills and their keys so the generated file is
  // deterministic. This keeps committed config diffs stable and lets the verify
  // gate byte-compare a regenerated config against the committed one.
  return sortConfig(result);
}

/** Return a copy with skill names and each skill's keys sorted lexicographically. */
function sortConfig(
  config: Record<string, Record<string, unknown>>,
): Record<string, Record<string, unknown>> {
  const sorted: Record<string, Record<string, unknown>> = {};
  for (const skillName of Object.keys(config).sort()) {
    const inner = config[skillName]!;
    const sortedInner: Record<string, unknown> = {};
    for (const key of Object.keys(inner).sort()) {
      sortedInner[key] = inner[key];
    }
    sorted[skillName] = sortedInner;
  }
  return sorted;
}

/** Filename of the generated per-target config. */
export const CONFIG_FILENAME = "skill-sync.config.yaml";

const CONFIG_HEADER =
  "# Generated by skill-sync. Do not edit manually.\n# Re-run `skill-sync sync` to regenerate.\n";

/**
 * Serialize a merged config to the canonical on-disk form (single header +
 * deterministic YAML). This is the ONE serializer; both the writer and the
 * verify gate use it so a regenerated config byte-matches the committed one.
 */
export function serializeProjectConfig(config: Record<string, Record<string, unknown>>): string {
  return CONFIG_HEADER + stringifyYaml(config);
}

/**
 * Write the generated skill-sync.config.yaml into a target directory.
 */
export async function writeProjectConfig(
  targetDir: string,
  config: Record<string, Record<string, unknown>>,
): Promise<string> {
  await mkdir(targetDir, { recursive: true });
  const configPath = join(targetDir, CONFIG_FILENAME);
  await writeFile(configPath, serializeProjectConfig(config), "utf-8");
  return configPath;
}

/**
 * Validate that manifest config values match declared config_inputs.
 * Returns warnings for unknown keys and type mismatches.
 */
export function validateConfigOverrides(
  manifestConfig: Record<string, Record<string, unknown>>,
  installedSkills: SkillPackage[],
): string[] {
  const warnings: string[] = [];
  const skillMap = new Map(installedSkills.map((s) => [s.name, s]));

  for (const [skillName, config] of Object.entries(manifestConfig)) {
    const pkg = skillMap.get(skillName);
    if (!pkg) {
      warnings.push(`Config for "${skillName}" has no matching installed skill`);
      continue;
    }

    if (!pkg.meta?.configInputs?.length) {
      // Skill doesn't declare config_inputs — config values are passthrough
      continue;
    }

    const declaredKeys = new Set(
      pkg.meta.configInputs.map((ci) => {
        const parts = ci.key.split(".");
        return parts.length === 2 && parts[0] === skillName ? parts[1]! : ci.key;
      }),
    );

    for (const key of Object.keys(config)) {
      if (!declaredKeys.has(key)) {
        warnings.push(`Config key "${skillName}.${key}" is not declared in skill's config_inputs`);
      }
    }
  }

  return warnings;
}
